/* kernel.c -- freestanding entry + the three device drivers the game needs
 * beyond graphics: COM1 serial (debug/test mirror), polled PS/2 keyboard,
 * and a PIT-based millisecond clock (+ the PC speaker for beeps).
 *
 * boot64.S (verbatim from ShivyC's mbos demo) enters long mode and calls
 * kmain(). kmain brings the devices up, then hands control to the rpython
 * game: py2c has translated game.py/engine.py/levels.py into C objects that
 * link right into this kernel; their module-level state is set up by the
 * generated <module>_init() functions, and snake_main() never returns.
 */
#include "kernel.h"

/* generated by py2c from rpy/*.py (see Makefile) */
void levels_init(void);
void engine_init(void);
void game_init(void);
int  snake_main(void);

/* ---- COM1 serial -------------------------------------------------------- */
#define COM1 0x3F8

void ser_init(void) {
    outb(COM1 + 1, 0x00); outb(COM1 + 3, 0x80); outb(COM1 + 0, 0x03);
    outb(COM1 + 1, 0x00); outb(COM1 + 3, 0x03); outb(COM1 + 2, 0xC7);
    outb(COM1 + 4, 0x0B);
}
static void ser_putc(char c) {
    int spin = 100000;
    while (spin-- > 0 && (inb(COM1 + 5) & 0x20) == 0) { }
    outb(COM1, (u8)c);
}
void ser_puts(const char *s) {
    while (*s) { if (*s == '\n') ser_putc('\r'); ser_putc(*s++); }
}
/* The generated runtime's printf/puts land here (rt_freestanding.c). */
void con_putc(char c) { if (c == '\n') ser_putc('\r'); ser_putc(c); }
void con_puts(const char *s) { while (*s) con_putc(*s++); }

/* ---- polled PS/2 keyboard ----------------------------------------------- *
 * QEMU's i8042 speaks scancode set 1 (translation on) out of reset, so no
 * controller/device setup is needed: just drain port 0x60 when status bit 0
 * says a byte is waiting, skipping mouse bytes (status bit 5). 0xE0 starts
 * an extended sequence (arrow keys); bit 7 of the code is the break flag. */
static int kb_e0;

int kb_poll(void) {
    u8 st, sc;
    for (;;) {
        st = inb(0x64);
        if ((st & 0x01) == 0) return -1;        /* nothing pending */
        sc = inb(0x60);
        if (st & 0x20) continue;                /* AUX (mouse) byte: discard */
        if (sc == 0xE0) { kb_e0 = 1; continue; }
        if (sc == 0xE1) { kb_e0 = 0; continue; }/* pause seq: ignore tail    */
        {
            int ev = (sc & 0x7F) | ((sc & 0x80) ? 0x80 : 0) | (kb_e0 ? 0x100 : 0);
            kb_e0 = 0;
            return ev;
        }
    }
}

/* ---- PIT millisecond clock ---------------------------------------------- *
 * Channel 0, mode 2, full 65536 divisor: the 16-bit counter sweeps down at
 * 1193182 Hz and reloads every 54.9 ms. Latching it on every call and
 * accumulating the down-count deltas gives a monotonic tick count with no
 * interrupts, as long as we are called faster than the reload period --
 * which any polling game loop does many times over. */
static u32 pit_prev;
static u64 pit_ticks;
static int pit_up;

static u32 pit_read(void) {
    u32 lo, hi;
    outb(0x43, 0x00);                            /* latch channel 0 */
    lo = inb(0x40);
    hi = inb(0x40);
    return (hi << 8) | lo;
}

u32 time_ms(void) {
    u32 cur;
    if (!pit_up) {
        outb(0x43, 0x34);                        /* ch0, lo/hi, mode 2 */
        outb(0x40, 0x00);                        /* divisor 65536      */
        outb(0x40, 0x00);
        pit_prev = pit_read();
        pit_ticks = 0;
        pit_up = 1;
    }
    cur = pit_read();
    pit_ticks += (u32)((pit_prev - cur) & 0xFFFF);   /* counts DOWN */
    pit_prev = cur;
    return (u32)(pit_ticks * 1000u / 1193182u);
}

/* ---- PC speaker (PIT channel 2) ----------------------------------------- */
void spk_on(u32 hz) {
    u32 div;
    if (hz < 20) hz = 20;
    div = 1193182u / hz;
    outb(0x43, 0xB6);                            /* ch2, lo/hi, mode 3 */
    outb(0x42, (u8)(div & 0xFF));
    outb(0x42, (u8)((div >> 8) & 0xFF));
    outb(0x61, inb(0x61) | 0x03);                /* gate + data enable */
}
void spk_off(void) {
    outb(0x61, inb(0x61) & (u8)~0x03);
}

/* ---- kernel entry -------------------------------------------------------- */
void kmain(unsigned int magic, void *mbi) {
    (void)magic; (void)mbi;

    ser_init();
    ser_puts("\n[snake] boot ok (rpython game path)\n");

    if (gfx_init(MBOS_GFX_W, MBOS_GFX_H) != 0) {
        ser_puts("[snake] no framebuffer -- halting\n");
        for (;;) __asm__ volatile ("hlt");
    }

    time_ms();                                   /* start the PIT clock */

    /* Python "import time": run each generated module's top-level, leaf
     * modules first, then enter the game. snake_main() runs the menu/game
     * loop forever. */
    levels_init();
    engine_init();
    game_init();
    snake_main();

    ser_puts("[snake] snake_main returned -- halting\n");
    for (;;) __asm__ volatile ("hlt");
}
